Add Linux 5.1+ compat fix for deprecated CRYPTO_TFM_REQ_WEAK_KEY
GostCrypt/linux-crypto pull request #5
Opened 2019-06-11 08:45 UTC by ColinIanKing

With Linux 5.1 onwards, CRYPTO_TFM_REQ_WEAK_KEY has been deprecated and
renamed to CRYPTO_TFM_REQ_FORBID_WEAK_KEYS.  Add a compat check to cater
for this change as introduced into Linux with commit 231baecdef7a9065799
("crypto: clarify name of WEAK_KEY request flag")

Signed-off-by: Colin Ian King <colin.king@canonical.com>

2019-06-23 12:34 UTC, lumag commented on gost28147_modes.c
> +	memmove(walk->iv, iv, bsize);
Hmm. Mainline linux CFB code doesn't contain this memcpy. I should probably drop it alltogether. Would you mind backporting  6c2e322b3621dc8be72e5c86d4fdb587434ba625 instead?

2019-06-23 12:38 UTC, lumag commented
As for the 5.1 I've included a bit different fix. Could you please check whether it works for you?

2019-06-24 07:09 UTC, ColinIanKing commented
> As for the 5.1 I've included a bit different fix. Could you please check whether it works for you?

Apologies, but I can't see the fix you are referring to. Any hint which commit that is?

2019-06-24 07:34 UTC, ColinIanKing commented
I've force pushed the backport of commit  crypto: cfb - remove bogus memcpy() with src == dest to my repo and requesting a merge of this.

2019-06-25 15:32 UTC, lumag requested changes

2019-06-25 15:32 UTC, lumag commented on gost28147_modes.c
>  		memcpy(iv, dst, bsize);
This line (`memcpy`) results in tests failure. Please remove it, as done in the original commit.

2019-06-25 15:34 UTC, lumag commented
> > As for the 5.1 I've included a bit different fix. Could you please check whether it works for you?
> 
> Apologies, but I can't see the fix you are referring to. Any hint which commit that is?

My fault, I've pushed it to the tag 0.3.1, but failed to push to master branch. Should be fixed now.

2019-06-25 15:35 UTC, lumag commented
@ColinIanKing I'll tag 0.3.2 after merging this pull request and upload it to Debian.

2019-06-26 20:36 UTC, lumag commented
Merged manually. Closing. Thanks @ColinIanKing

2019-06-26 20:37 UTC, closed without merging